# .github/workflows/build-gcp-dns-updater.yaml
name: Build GCP DNS Updater Image

on:
  push:
    branches:
      - main
    paths:
      - 'docker_images/gcp-dns-updater/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Required for pushing to GitHub Packages if used, good practice anyway

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: docker.${{ secrets.NOMAD_VAR_tld }}
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Build Image using Makefile
        env:
          NOMAD_VAR_tld: ${{ secrets.NOMAD_VAR_tld }}
        run: make build-gcp-dns-updater

      - name: Push Image
        run: docker push docker.${{ secrets.NOMAD_VAR_tld }}/gcp-dns-updater:latest
